package(default_visibility = ["//:__pkg__"],)

cc_library(
	name = "dlx_internal",
	hdrs = ["dlx_internal.h"],
	deps = [
	     ":cell",
	     ":matrix",
	     ":policies",
	     ":visitor",
	]
)

cc_library(
	name = "cell",
	hdrs = ["cell.h"],
)

cc_library(
	name = "matrix",
	hdrs = ["matrix.h"],
)

cc_library(
	name = "policies",
	hdrs = ["policies.h"],
)

cc_library(
	name = "visitor",
	hdrs = ["visitor.h"],
)
